### ISSUE TITLE
IntelligentSelect

### ISSUE THREAD

**Issue by ChangSh** [ChangSh/Wind#3]
**智能联想**，一个小功能，可以实现现在很多搜索框都用到的联想功能，目前只能根据输入联想。 
### CSS
``` css
/*这个DIV用来装联想出来的一条条记录。
  通过absolute绝对定位 + z-index属性来使DIV堆在页面元素的最上方。
  宽度自适应，高度限制。
  overflow滚动条。
*/
.divcontent {
            border: 1px solid #E3E3E3;
            position: absolute;
            z-index: 999;
            height: 200px;
            overflow: auto;
        }

        .appendcontent {
            border-left: 1px solid #E3E3E3;
            border-right: 1px solid #E3E3E3;
            border-bottom: 1px solid #E3E3E3;
            cursor: pointer;
            background: #FFFFFF;
        }
```

### JS
``` javascript
function projchange() {
        var cprojectName = $("#txtProjName").val();
        if (cprojectName != "") {
            $.ajax({
                type: "post",
                url: url,
                data: { cprojectName: cprojectName },
                dataType: "json",
                success: function (dt) {
                    $("#projcontent").html(""); //删除原有数据
                    if (dt.Rows.length > 0) {
                        for (var i = 0; i < dt.Rows.length; i++) {
                            $("#projcontent").append('<div  class="appendcontent" onmouseover="this.style.backgroundColor=\'#DBDBDB\'" onmouseout="this.style.backgroundColor=\'#FFFFFF\'"  id ="' + dt.Rows[i].CustId + '" onclick="projmousedown(this)">' + dt.Rows[i].CustName + '</div>');
                        }
                        $("#projcontent").slideDown(); //以滑动方式显示提示
                    }
                }
            });
        } else {
            $("#projcontent").html(""); //删除原有数据
        }
    }
    //选择其中的提示内容
    function projmousedown(object) {
        $("#txtProjName").val($(object).text());

        var cprojectId = $(object).attr("id");
        $("#txtProjId").val(cprojectId);
        $("#projcontent").fadeOut();  //以淡出效果来隐藏

    }
    //文档框失去焦点，隐藏提示内容
    function projlost() {
        $("#projcontent").fadeOut(); //以淡出效果来隐藏
    }
```

### HTML
``` html
<input type="text" id="txtProjName" onkeyup="projchange()" onblur="projlost()" />
<input type="hidden" id="txtProjId" />
 
<div id="projcontent" class="divcontent"></div>

```
